name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
      - 'pnpm-lock.yaml'
      - '!**.md'
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
      - 'pnpm-lock.yaml'
      - '!**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  # https://github.com/nodejs/corepack/issues/612#issuecomment-2631462297
  # Corepack is only used in tests. This isn't required for other workflows.
  # This sets the old and new integrity keys for corepack to download different
  # package managers signed with different keys.
  COREPACK_INTEGRITY_KEYS: '{"npm":[{"expires":"2025-01-29T00:00:00.000Z","keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="},{"expires":null,"keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6Ya7W++7aUPzvMTrezH6Ycx3c+HOKYCcNGybJZSCJq/fd7Qa8uuAKtdIkUQtQiEKERhAmE5lMMJhP8OkDOa2g=="}]}'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 22]
        include:
          - os: windows-latest
            node: 22
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      # Bun is only used in tests. This isn't required for other workflows.
      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: pnpm install

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 22 }}
        name: Lint
        run: pnpm lint

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 22 }}
        name: Typecheck
        run: pnpm typecheck

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 22 }}
        name: Lint with publint
        run: pnpm lint-publint

      - name: Run tests
        run: pnpm test
