name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.changeset/**'
      - '.github/workflows/release.yml'
      - 'pnpm-lock.yaml'

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'bluwy/publint'
    name: Release
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # OpenID Connect token needed for provenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for changelog generation
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          commit: Release packages
          title: Release packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
